apiVersion: v1
kind: Service
metadata:
  name: redis-api
  labels:
    app: redis-api
spec:
  type: ClusterIP
  selector:
    app: redis-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
